package ru.bmstu.hoiu3.game_objects;

public enum GameObjectType {
    GAME_OBJECT_TYPE_HERO,
    GAME_OBJECT_TYPE_OPPONENT,
    GAME_OBJECT_TYPE_MATVEI,
    GAME_OBJECT_TYPE_TREASURE,
    GAME_OBJECT_TYPE_TREASURE_SMALL,
    GAME_OBJECT_TYPE_TREASURE_BIG,
    GAME_OBJECT_TYPE_TREASURE_SPECIAL,
    GAME_OBJECT_TYPE_CASTLE,
    GAME_OBJECT_TYPE_ENEMY,
    GAME_OBJECT_TYPE_CURSOR,
    GAME_OBJECT_TYPE_ARMY,
    GAME_OBJECT_TYPE_PATH
}