public enum GameObjectType {
    GAME_OBJECT_TYPE_HERO,
    GAME_OBJECT_TYPE_OPPONENT,
    GAME_OBJECT_TYPE_TREASURE,
    GAME_OBJECT_TYPE_CASTLE,
    GAME_OBJECT_TYPE_ENEMY,
    GAME_OBJECT_TYPE_CURSOR,
}